cloud.aws.credentials.useDefaultAwsCredentialsChain: true
#cloud.aws.region.static: local
cloud.aws.stack.auto: false
spring.autoconfigure.exclude: org.springframework.cloud.aws.autoconfigure.metrics.CloudWatchExportAutoConfiguration
