cloud.aws.credentials.useDefaultAwsCredentialsChain: true
cloud:
   aws:
      region:
         static: eu-west-1
      stack:
         auto: false
      credentials:
         secretKey: test
         accessKey: test
#spring.autoconfigure.exclude: org.springframework.cloud.aws.autoconfigure.metrics.CloudWatchExportAutoConfiguration

localstack.aws.endpoint: http://localhost:4566